### ISSUE TITLE
chrome_dump_pdf - convert a local HTML to PDF

### ISSUE THREAD

**Issue by stephLH** [hrbrmstr/decapitated#4]
Hi!
Would it be possible to add the possibility to convert a local HTML file to PDF ?
My use case is to convert an ioslides HTML generated by the `rmarkdown` package.

**Comment by hrbrmstr** [comment]
(missed this…horrendous summer)

have you tried it with a `file:///` URL?

**Comment by stephLH** [comment]
Thank you!
